<?php

return [

	'1' => ['cn' => function($arr) {return "赛点"; }, 'en' => function($arr) {return "Match Point"; }, ],
	'10' => ['cn' => function($arr) {return "$arr[2] 第$arr[1]个Ace/二发Ace"; }, 'en' => function($arr) {return "Ace on 2nd serve - Ace #$arr[1] for $arr[2]"; }, ],
	'11' => ['cn' => function($arr) {return "获胜者: $arr[1]"; }, 'en' => function($arr) {return "Winner: $arr[1]"; }, ],
	'12' => ['cn' => function($arr) {return "获胜者: $arr[1]"; }, 'en' => function($arr) {return "Winners: $arr[1]"; }, ],
	'13' => ['cn' => function($arr) {return "$arr[1] 本组第$arr[2]个双误"; }, 'en' => function($arr) {return "Double Fault $arr[1] - #$arr[2] for the Team"; }, ],
	'14' => ['cn' => function($arr) {return "$arr[1] 本组第$arr[2]个Ace"; }, 'en' => function($arr) {return "Ace $arr[1] - #$arr[2] for the Team"; }, ],
	'15' => ['cn' => function($arr) {return "$arr[1] 本组第$arr[2]个Ace/二发Ace"; }, 'en' => function($arr) {return "Ace on 2nd serve $arr[1] - #$arr[2] for the Team"; }, ],
	'16' => ['cn' => function($arr) {return "因雨水暂停"; }, 'en' => function($arr) {return "Match Suspended - Rain"; }, ],
	'17' => ['cn' => function($arr) {return "因昏暗暂停"; }, 'en' => function($arr) {return "Match Suspended - Darkness"; }, ],
	'18' => ['cn' => function($arr) {return "因酷热暂停"; }, 'en' => function($arr) {return "Match Suspended - Heat"; }, ],
	'19' => ['cn' => function($arr) {return "比赛暂停"; }, 'en' => function($arr) {return "Match Suspended"; }, ],
	'2' => ['cn' => function($arr) {return "$arr[1]个赛点"; }, 'en' => function($arr) {return "$arr[1] Match Points"; }, ],
	'20' => ['cn' => function($arr) {return "退赛"; }, 'en' => function($arr) {return "by Retirement"; }, ],
	'21' => ['cn' => function($arr) {return "$arr[1]被罚分"; }, 'en' => function($arr) {return "Point Penalty Against $arr[1]"; }, ],
	'22' => ['cn' => function($arr) {return "$arr[1]被罚局"; }, 'en' => function($arr) {return "Game Penalty Against $arr[1]"; }, ],
	'23' => ['cn' => function($arr) {return "$arr[1]被罚超时"; }, 'en' => function($arr) {return "Time Penalty Against $arr[1]"; }, ],
	'24' => ['cn' => function($arr) {return "被罚出场"; }, 'en' => function($arr) {return "by Default"; }, ],
	'25' => ['cn' => function($arr) {return "局点"; }, 'en' => function($arr) {return "Game Point"; }, ],
	'26' => ['cn' => function($arr) {return "$arr[1]个局点"; }, 'en' => function($arr) {return "$arr[1] Game Points"; }, ],
	'27' => ['cn' => function($arr) {return "二发脚误"; }, 'en' => function($arr) {return "Foot fault - 2nd Serve"; }, ],
	'28' => ['cn' => function($arr) {return "$arr[2] 第$arr[1]个双误/脚误"; }, 'en' => function($arr) {return "Foot fault - Double Fault #$arr[1] for $arr[2]"; }, ],
	'29' => ['cn' => function($arr) {return "$arr[1] 本组第$arr[2]个双误/脚误"; }, 'en' => function($arr) {return "Foot fault - Double Fault $arr[1] - #$arr[2] for the team"; }, ],
	'3' => ['cn' => function($arr) {return "破发点"; }, 'en' => function($arr) {return "Break Point"; }, ],
	'30' => ['cn' => function($arr) {return "擦网重发"; }, 'en' => function($arr) {return "Let"; }, ],
	'31' => ['cn' => function($arr) {return "平分"; }, 'en' => function($arr) {return "Deuce"; }, ],
	'32' => ['cn' => function($arr) {return "占先"; }, 'en' => function($arr) {return "Advantage"; }, ],
	'33' => ['cn' => function($arr) {return "双误"; }, 'en' => function($arr) {return "Double Fault"; }, ],
	'34' => ['cn' => function($arr) {return "一发失误"; }, 'en' => function($arr) {return "First Serve Fault"; }, ],
	'35' => ['cn' => function($arr) {return "一发脚误"; }, 'en' => function($arr) {return "First Serve Foot Fault"; }, ],
	'36' => ['cn' => function($arr) {return "二发脚误"; }, 'en' => function($arr) {return "Double Foot Fault"; }, ],
	'37' => ['cn' => function($arr) {return "简介/头对头"; }, 'en' => function($arr) {return "Bios/Head to Head"; }, ],
	'38' => ['cn' => function($arr) {return "不战而胜"; }, 'en' => function($arr) {return "by Walkover"; }, ],
	'4' => ['cn' => function($arr) {return "$arr[1]个破发点"; }, 'en' => function($arr) {return "$arr[1] break points"; }, ],
	'5' => ['cn' => function($arr) {return "盘点"; }, 'en' => function($arr) {return "Set Point"; }, ],
	'6' => ['cn' => function($arr) {return "$arr[1]个盘点"; }, 'en' => function($arr) {return "$arr[1] set points"; }, ],
	'7' => ['cn' => function($arr) {return "二发"; }, 'en' => function($arr) {return "2nd serve"; }, ],
	'8' => ['cn' => function($arr) {return "$arr[2] 第$arr[1]个双误"; }, 'en' => function($arr) {return "Double Fault #$arr[1] for $arr[2]"; }, ],
	'9' => ['cn' => function($arr) {return "$arr[2] 第$arr[1]个Ace"; }, 'en' => function($arr) {return "Ace - #$arr[1] for $arr[2]"; }, ],

	'Break point' => ['cn' => '破发点', 'en' => 'Break Point', ],
	'Game point' => ['cn' => '局点', 'en' => 'Game Point', ],
	'Set point' => ['cn' => '盘点', 'en' => 'Set Point', ],
	'Match point' => ['cn' => '赛点', 'en' => 'Match Point', ],
	'Set' => ['cn' => '赛盘结束', 'en' => 'Set Finished', ],
	'Game' => ['cn' => '保发', 'en' => 'Hold the Game', ],
	'Match' => ['cn' => '比赛结束', 'en' => 'Match Completed', ],
	'Break' => ['cn' => '破发', 'en' => 'Break', ],

	'Ace' => ['cn' => 'Ace', 'en' => 'Ace', ],
	'Let' => ['cn' => '擦网重发', 'en' => 'Let', ],
	'Fault' => ['cn' => '失误', 'en' => 'Fault', ],
	'Double Fault' => ['cn' => '双误', 'en' => 'Double Fault', ],
	'Foot Fault' => ['cn' => '脚误', 'en' => 'Foot Fault', ],
	'Forehand Winner' => ['cn' => '正手制胜分', 'en' => 'Forehand Winner', ],
	'Backhand Winner' => ['cn' => '反手制胜分', 'en' => 'Backhand Winner', ],
	'Overhead Winner' => ['cn' => '过顶制胜分', 'en' => 'Overhead Winner', ],
	'Volley Winner' => ['cn' => '截击制胜分', 'en' => 'Volley Winner', ],
	'Net Winner' => ['cn' => '网前制胜分', 'en' => 'Net Winner', ],
	'Service Winner' => ['cn' => '发球制胜分', 'en' => 'Service Winner', ],
	'Return Of Service Winner' => ['cn' => '接发球制胜分', 'en' => 'Return Of Service Winner', ],
	'Forehand Unforced Error' => ['cn' => '正手非受迫失误', 'en' => 'Forehand Unforced Error', ],
	'Backhand Unforced Error' => ['cn' => '反手非受迫失误', 'en' => 'Backhand Unforced Error', ],
	'Overhead Unforced Error' => ['cn' => '过顶非受迫失误', 'en' => 'Overhead Unforced Error', ],
	'Volley Unforced Error' => ['cn' => '截击非受迫失误', 'en' => 'Volley Unforced Error', ],
	'Net Unforced Error' => ['cn' => '网前非受迫失误', 'en' => 'Net Unforced Error', ],
	'Forehand Forced Error' => ['cn' => '正手受迫失误', 'en' => 'Forehand Forced Error', ],
	'Backhand Forced Error' => ['cn' => '反手受迫失误', 'en' => 'Backhand Forced Error', ],
	'Overhead Forced Error' => ['cn' => '过顶受迫失误', 'en' => 'Overhead Forced Error', ],
	'Volley Forced Error' => ['cn' => '截击受迫失误', 'en' => 'Volley Forced Error', ],
];
