<?php

return [
	'Final' => ['cn' => '决赛', 'en' => 'Final', ],
	'Bronze' => ['cn' => '铜牌赛', 'en' => 'Bronze', ],
	'F' => ['cn' => '决赛', 'en' => 'Final', ],
	'Semifinals' => ['cn' => '半决赛', 'en' => 'SF', ],
	'Semifinal' => ['cn' => '半决赛', 'en' => 'SF', ],
	'Round Robin' => ['cn' => '小组赛', 'en' => 'RR', ],
	'Round Robin A' => ['cn' => '小组赛A', 'en' => 'RR-A', ],
	'Round Robin B' => ['cn' => '小组赛B', 'en' => 'RR-B', ],
	'Round Robin C' => ['cn' => '小组赛C', 'en' => 'RR-C', ],
	'Round Robin D' => ['cn' => '小组赛D', 'en' => 'RR-D', ],
	'Play-off' => ['cn' => '保级附加', 'en' => 'PO', ],
	'PPO Play-off' => ['cn' => '升级附加', 'en' => 'PPO', ],
	'PO Play-off' => ['cn' => '附加赛', 'en' => 'PO', ],
	'PP3-4 Play-off' => ['cn' => '3-4名附加', 'en' => 'PO3-4', ],
	'PP5-8 Play-off' => ['cn' => '5-8名附加', 'en' => 'PO5-8', ],
	'1st Round Play-off' => ['cn' => '一轮附加', 'en' => 'PO R1', ],
	'2nd Round Play-off' => ['cn' => '二轮附加', 'en' => 'PO R2', ],
	'RR' => ['cn' => '小组赛', 'en' => 'RR', ],
	'RR-A' => ['cn' => '小组赛A', 'en' => 'RR-A', ],
	'RR-B' => ['cn' => '小组赛B', 'en' => 'RR-B', ],
	'RR-C' => ['cn' => '小组赛C', 'en' => 'RR-C', ],
	'RR-D' => ['cn' => '小组赛D', 'en' => 'RR-D', ],
	'SF' => ['cn' => '半决赛', 'en' => 'SF', ],
	'S' => ['cn' => '半决赛', 'en' => 'SF', ],
	'Quarterfinals' => ['cn' => '1/4决赛', 'en' => 'QF', ],
	'Quarterfinal' => ['cn' => '1/4决赛', 'en' => 'QF', ],
	'QF' => ['cn' => '1/4决赛', 'en' => 'QF', ],
	'Q' => ['cn' => '1/4决赛', 'en' => 'QF', ],
	'4th Round' => ['cn' => '第四轮', 'en' => 'R4', ],
	'3rd Round' => ['cn' => '第三轮', 'en' => 'R3', ],
	'2nd Round' => ['cn' => '第二轮', 'en' => 'R2', ],
	'1st Round' => ['cn' => '第一轮', 'en' => 'R1', ],
	'R4' => ['cn' => '第四轮', 'en' => 'R4', ],
	'R3' => ['cn' => '第三轮', 'en' => 'R3', ],
	'R2' => ['cn' => '第二轮', 'en' => 'R2', ],
	'R1' => ['cn' => '第一轮', 'en' => 'R1', ],
	'Q - 1st Round' => ['cn' => 'Q第一轮', 'en' => 'QR1', ],
	'Q - 2nd Round' => ['cn' => 'Q第二轮', 'en' => 'QR2', ],
	'Q - 3rd Round' => ['cn' => 'Q第三轮', 'en' => 'QR3', ],
	'Q - 4th Round' => ['cn' => 'Q第四轮', 'en' => 'QR4', ],
	'Q - Final Round' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-R1' => ['cn' => 'Q第一轮', 'en' => 'QR1', ],
	'Q-R2' => ['cn' => 'Q第二轮', 'en' => 'QR2', ],
	'Q-R3' => ['cn' => 'Q第三轮', 'en' => 'QR3', ],
	'Q-R4' => ['cn' => 'Q第四轮', 'en' => 'QR4', ],
	'QR1' => ['cn' => 'Q第一轮', 'en' => 'QR1', ],
	'QR2' => ['cn' => 'Q第二轮', 'en' => 'QR2', ],
	'QR3' => ['cn' => 'Q第三轮', 'en' => 'QR3', ],
	'QR4' => ['cn' => 'Q第四轮', 'en' => 'QR4', ],
	'QRF' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-Final' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q - R64' => ['cn' => 'Q-R64', 'en' => 'QR64', ],
	'Q - R32' => ['cn' => 'Q-R32', 'en' => 'QR32', ],
	'Q - R16' => ['cn' => 'Q-R16', 'en' => 'QR16', ],
	'Q - Q' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q - S' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-R64' => ['cn' => 'Q-R64', 'en' => 'QR64', ],
	'Q-R32' => ['cn' => 'Q-R32', 'en' => 'QR32', ],
	'Q-R16' => ['cn' => 'Q-R16', 'en' => 'QR16', ],
	'Q-Q' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-R8' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-R4' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Q-S' => ['cn' => 'Q决胜轮', 'en' => 'QRF', ],
	'Qualification round' => ['cn' => '资格赛', 'en' => 'QR', ],
	'Q-Round' => ['cn' => '资格赛', 'en' => 'QR', ],
];
