<?php

return [

	'test' => [
		'css' => [
			'bootstrap' => PHP_SAPI === 'cli' ? false : url('/test_css/bootstrap.min.css'),
			'emoji' => PHP_SAPI === 'cli' ? false : url('/test_css/emoji.css'),
			'datatables' => PHP_SAPI === 'cli' ? false : url('/test_css/datatables.min.css'),
			'swiper' => PHP_SAPI === 'cli' ? false : url('/test_css/swiper-3.4.0.min.css'),
			'pickmeup' => PHP_SAPI === 'cli' ? false : url('/test_css/pickmeup.css?') . "t=" . time(),
			'optionpicker' => PHP_SAPI === 'cli' ? false : url('/test_css/optionpicker.css?') . "t=" . time(),

			'base' => PHP_SAPI === 'cli' ? false : url('/test_css/base.css?') . "t=" . time(),
			'frame' => PHP_SAPI === 'cli' ? false : url('/test_css/frame.css?') . "t=" . time(),
			'light' => PHP_SAPI === 'cli' ? false : url('/test_css/light.css?') . "t=" . time(),
			'dark' => PHP_SAPI === 'cli' ? false : url('/test_css/dark.css?') . "t=" . time(),
			'load' => PHP_SAPI === 'cli' ? false : url('/test_css/loading.css?') . "t=" . time(),
			'home' => PHP_SAPI === 'cli' ? false : url('/test_css/home.css?') . "t=" . time(),
			'rankpage' => PHP_SAPI === 'cli' ? false : url('/test_css/rankpage.css?') . "t=" . time(),
			'breakdown' => PHP_SAPI === 'cli' ? false : url('/test_css/breakdown.css?') . "t=" . time(),
			'result' => PHP_SAPI === 'cli' ? false : url('/test_css/result.css?') . "t=" . time(),
			'stat' => PHP_SAPI === 'cli' ? false : url('/test_css/stat.css?') . "t=" . time(),
			'pbp' => PHP_SAPI === 'cli' ? false : url('/test_css/pbp.css?') . "t=" . time(),
			'h2hDetail' => PHP_SAPI === 'cli' ? false : url('/test_css/h2hDetail.css?') . "t=" . time(),
			'h2h' => PHP_SAPI === 'cli' ? false : url('/test_css/h2h.css?') . "t=" . time(),
			'draw' => PHP_SAPI === 'cli' ? false : url('/test_css/draw.css?') . "t=" . time(),
			'dc' => PHP_SAPI === 'cli' ? false : url('/test_css/dc.css?') . "t=" . time(),
			'dcpk' => PHP_SAPI === 'cli' ? false : url('/test_css/dcpk.css?') . "t=" . time(),
			'evolv' => PHP_SAPI === 'cli' ? false : url('/test_css/evolv.css?') . "t=" . time(),
			'gs' => PHP_SAPI === 'cli' ? false : url('/test_css/gs.css?') . "t=" . time(),
		],
		'js' => [
			'jquery' => PHP_SAPI === 'cli' ? false : url('/test_js/jquery.min.js'),
			'encode' => PHP_SAPI === 'cli' ? false : url('/test_js/encode.js'),
			'datatables' => PHP_SAPI === 'cli' ? false : url('/test_js/datatables.min.js'),
			'swiper' => PHP_SAPI === 'cli' ? false : url('/test_js/swiper-3.4.0.jquery.min.js'),
			'echarts' => PHP_SAPI === 'cli' ? false : url('/test_js/echarts.common.min.js'),
			'pickmeup' => PHP_SAPI === 'cli' ? false : url('/test_js/pickmeup.js'),
			'optionpicker' => PHP_SAPI === 'cli' ? false : url('/test_js/optionpicker.js?') . "t=" . time(),

			'base' => PHP_SAPI === 'cli' ? false : url('/test_js/base.js?') . "t=" . time(),
			'frame' => PHP_SAPI === 'cli' ? false : url('/test_js/frame.js?') . "t=" . time(),
			'rankpage' => PHP_SAPI === 'cli' ? false : url('/test_js/rankpage.js?') . "t=" . time(),
			'breakdown' => PHP_SAPI === 'cli' ? false : url('/test_js/breakdown.js?') . "t=" . time(),
			'result' => PHP_SAPI === 'cli' ? false : url('/test_js/result.js?') . "t=" . time(),
			'h2h' => PHP_SAPI === 'cli' ? false : url('/test_js/h2h.js?') . "t=" . time(),
			'draw' => PHP_SAPI === 'cli' ? false : url('/test_js/draw.js?') . "t=" . time(),
			'dc' => PHP_SAPI === 'cli' ? false : url('/test_js/dc.js?') . "t=" . time(),
			'dcRank' => PHP_SAPI === 'cli' ? false : url('/test_js/dcRank.js?') . "t=" . time(),
			'dcpk' => PHP_SAPI === 'cli' ? false : url('/test_js/dcpk.js?') . "t=" . time(),
			'guessrank' => PHP_SAPI === 'cli' ? false : url('/test_js/guessrank.js?') . "t=" . time(),
			'guesscalendar' => PHP_SAPI === 'cli' ? false : url('/test_js/guesscalendar.js?') . "t=" . time(),
			'guessSign' => PHP_SAPI === 'cli' ? false : url('/test_js/guessSign.js?') . "t=" . time(),
			'activity' => PHP_SAPI === 'cli' ? false : url('/test_js/activity.js?') . "t=" . time(),
			'schedule' => PHP_SAPI === 'cli' ? false : url('/test_js/schedule.js?') . "t=" . time(),
			'interpolate' => PHP_SAPI === 'cli' ? false : url('/test_js/interpolate.js?') . "t=" . time(),
			'gs' => PHP_SAPI === 'cli' ? false : url('/test_js/gs.js?') . "t=" . time(),
			'profile' => PHP_SAPI === 'cli' ? false : url('/test_js/profile.js?') . "t=" . time(),
			'topn' => PHP_SAPI === 'cli' ? false : url('/test_js/topn.js?') . "t=" . time(),
			'vue' => PHP_SAPI === 'cli' ? false : url('/test_js/vue.js'),
		],
	],
	'common' => [
		'css' => [
			'bootstrap' => PHP_SAPI === 'cli' ? false : url('/css/bootstrap.min.css'),
			'emoji' => PHP_SAPI === 'cli' ? false : url('/css/emoji.css'),
			'datatables' => PHP_SAPI === 'cli' ? false : url('/css/datatables.min.css'),
			'swiper' => PHP_SAPI === 'cli' ? false : url('/css/swiper-3.4.0.min.css'),
			'pickmeup' => PHP_SAPI === 'cli' ? false : url('/css/pickmeup.css?') . "t=201906061050",
			'optionpicker' => PHP_SAPI === 'cli' ? false : url('/css/optionpicker.css?') . "t=201905102245",

			'base' => PHP_SAPI === 'cli' ? false : url('/css/base.css?') . "t=202002101240",
			'frame' => PHP_SAPI === 'cli' ? false : url('/css/frame.css?') . "t=202003011720",
			'light' => PHP_SAPI === 'cli' ? false : url('/css/light.css?') . "t=202101121545",
			'dark' => PHP_SAPI === 'cli' ? false : url('/css/dark.css?') . "t=202101121545",
			'load' => PHP_SAPI === 'cli' ? false : url('/css/loading.css?') . "t=201905022250",
			'home' => PHP_SAPI === 'cli' ? false : url('/css/home.css?') . "t=201905271245",
			'rankpage' => PHP_SAPI === 'cli' ? false : url('/css/rankpage.css?') . "t=201812300235",
			'breakdown' => PHP_SAPI === 'cli' ? false : url('/css/breakdown.css?') . "t=201812300235",
			'result' => PHP_SAPI === 'cli' ? false : url('/css/result.css?') . "t=202101121540",
			'stat' => PHP_SAPI === 'cli' ? false : url('/css/stat.css?') . "t=201812300235",
			'pbp' => PHP_SAPI === 'cli' ? false : url('/css/pbp.css?') . "t=201812300235",
			'h2hDetail' => PHP_SAPI === 'cli' ? false : url('/css/h2hDetail.css?') . "t=201905102245",
			'h2h' => PHP_SAPI === 'cli' ? false : url('/css/h2h.css?') . "t=201905102245",
			'draw' => PHP_SAPI === 'cli' ? false : url('/css/draw.css?') . "t=202003102215",
			'dc' => PHP_SAPI === 'cli' ? false : url('/css/dc.css?') . "t=201901111645",
			'dcpk' => PHP_SAPI === 'cli' ? false : url('/css/dcpk.css?') . "t=201901022216",
			'evolv' => PHP_SAPI === 'cli' ? false : url('/css/evolv.css?') . "t=201812300235",
			'gs' => PHP_SAPI === 'cli' ? false : url('/css/gs.css?') . "t=201812300235",
			'work-as-one' => PHP_SAPI === 'cli' ? false : url('/css/work-as-one.css?') . "t=201812300235",
		],
		'js' => [
			'jquery' => PHP_SAPI === 'cli' ? false : url('/js/jquery.min.js'),
			'encode' => PHP_SAPI === 'cli' ? false : url('/js/encode.js'),
			'datatables' => PHP_SAPI === 'cli' ? false : url('/js/datatables.min.js'),
			'swiper' => PHP_SAPI === 'cli' ? false : url('/js/swiper-3.4.0.jquery.min.js'),
			'echarts' => PHP_SAPI === 'cli' ? false : url('/js/echarts.common.min.js'),
			'pickmeup' => PHP_SAPI === 'cli' ? false : url('/js/pickmeup.js?') . "t=201906061052",
			'optionpicker' => PHP_SAPI === 'cli' ? false : url('/js/optionpicker.js?') . "t=201905102245",

			'base' => PHP_SAPI === 'cli' ? false : url('/js/base.js?') . "t=202001131250",
			'frame' => PHP_SAPI === 'cli' ? false : url('/js/frame.js?') . "t=201912191525",
			'rankpage' => PHP_SAPI === 'cli' ? false : url('/js/rankpage.js?') . "t=201812300235",
			'breakdown' => PHP_SAPI === 'cli' ? false : url('/js/breakdown.js?') . "t=201812300235",
			'result' => PHP_SAPI === 'cli' ? false : url('/js/result.js?') . "t=201903042254",
			'h2h' => PHP_SAPI === 'cli' ? false : url('/js/h2h.js?') . "t=201905102245",
			'draw' => PHP_SAPI === 'cli' ? false : url('/js/draw.js?') . "t=202001290035",
			'dc' => PHP_SAPI === 'cli' ? false : url('/js/dc.js?') . "t=201812300235",
			'dcRank' => PHP_SAPI === 'cli' ? false : url('/js/dcRank.js?') . "t=201812300235",
			'dcpk' => PHP_SAPI === 'cli' ? false : url('/js/dcpk.js?') . "t=201812300235",
			'guessrank' => PHP_SAPI === 'cli' ? false : url('/js/guessrank.js?') . "t=201812300235",
			'guesscalendar' => PHP_SAPI === 'cli' ? false : url('/js/guesscalendar.js?') . "t=201812300235",
			'guessSign' => PHP_SAPI === 'cli' ? false : url('/js/guessSign.js?') . "t=201812300235",
			'activity' => PHP_SAPI === 'cli' ? false : url('/js/activity.js?') . "t=201812300235",
			'schedule' => PHP_SAPI === 'cli' ? false : url('/js/schedule.js?') . "t=201812300235",
			'interpolate' => PHP_SAPI === 'cli' ? false : url('/js/interpolate.js?') . "t=201901152319",
			'gs' => PHP_SAPI === 'cli' ? false : url('/js/gs.js?') . "t=201812300235",
			'profile' => PHP_SAPI === 'cli' ? false : url('/js/profile.js?') . "t=201812300235",
			'topn' => PHP_SAPI === 'cli' ? false : url('/js/topn.js?') . "t=201812300235",
		],
	],
];
